import crypto from 'node:crypto';
import {ToobitDirectClient,rows} from './toobit-direct.js';
import {MarketDataEngine,fairPrice,inventorySnapshot,inventoryPolicy,buildDesiredQuotes,shouldRequote,evaluateRisk} from './maker-core.js';
import {SingleFlightRunner} from './single-flight.js';

const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const first=(d)=>Array.isArray(d)?(d[0]??{}):(d??{});
const normPositions=(data)=>rows(data).map(p=>({symbol:String(p.symbol??''),side:String(p.side??p.positionSide??''),position:finite(p.position),positionValue:Math.abs(finite(p.positionValue)),leverage:finite(p.leverage),unrealizedPnl:finite(p.unrealizedPnL??p.unrealizedPnl),realizedPnl:finite(p.realizedPnL??p.realizedPnl),riskRate:finite(p.riskRate??p.rr),liquidationPrice:finite(p.flp??p.liquidationPrice),avgPrice:finite(p.avgPrice??p.entryPrice)}));
const normOrders=(data)=>rows(data).map(o=>({orderId:String(o.orderId??''),clientOrderId:String(o.clientOrderId??''),side:String(o.side??'').toUpperCase(),positionSide:String(o.positionSide??'').toUpperCase(),status:String(o.status??'').toUpperCase(),price:finite(o.price),valueQuantity:finite(o.valueQuantity??o.executedNotional??o.origQty),time:finite(o.time??o.updateTime),createdAt:finite(o.time??o.updateTime,Date.now())}));
const isLiveStatus=(s)=>!s||['PENDING_NEW','NEW','PARTIALLY_FILLED'].includes(String(s).toUpperCase());

export class V49LiveRuntime{
  constructor({credentialStore,liveEnabled=false,symbol='BTC-SWAP-USDT',prefix='DKV49M_'}={}){if(!credentialStore)throw new Error('CREDENTIAL_STORE_REQUIRED');Object.assign(this,{credentialStore,liveEnabled,symbol,prefix});this.market=new MarketDataEngine(symbol);this.state='DISARMED';this.reason='CREDENTIAL_NOT_PROVISIONED';this.publicWs=false;this.privateWs=false;this.publicSocket=null;this.privateSocket=null;this.listenKey='';this.client=null;this.settings={quoteNotional:10,minQuoteNotional:5,minNetEdgeBps:1,requoteBps:2,minQuoteLifeMs:2500,maxOrderAgeMs:15000,dailyLossLimitUsdt:2,maxLeverageForDualSide:20,capitalUtilization:.7,requestedLeverage:10};this.account={balance:0,available:0,positions:[],todayPnl:0,feeBps:1.2};this.orders={bid:null,ask:null};this.tickSize=.1;this.apiErrorStreak=0;this.lastFair=null;this.lastDesired={bid:null,ask:null};this.started=false;this.timers=[];this.privateRefreshPending=false;this.lastError='';this.lastStopReason='';this.quoteRunner=new SingleFlightRunner(()=>this.#quoteOnce());}
  async initialize(){await this.#loadMarketSpec();this.#connectPublic();if(this.credentialStore.exists())await this.reloadCredential();this.timers.push(setInterval(()=>this.#refreshAccount().catch(()=>{}),5000),setInterval(()=>this.#watchdog().catch(()=>{}),1000),setInterval(()=>this.#keepalive().catch(()=>{}),25*60*1000));return this.status();}
  async shutdown(){this.started=false;await this.stop('SERVICE_SHUTDOWN');for(const t of this.timers)clearInterval(t);try{this.publicSocket?.close();this.privateSocket?.close();}catch{}return this.status();}
  setSettings(s={}){this.settings={...this.settings,quoteNotional:Math.max(0,finite(s.baseQuoteNotional??s.quoteNotional,this.settings.quoteNotional)),minNetEdgeBps:Math.max(0,finite(s.minNetEdgeBps,this.settings.minNetEdgeBps)),requoteBps:Math.max(.1,finite(s.requoteBps,this.settings.requoteBps)),minQuoteLifeMs:Math.max(500,finite(s.minQuoteLifeMs,this.settings.minQuoteLifeMs)),maxOrderAgeMs:Math.max(1000,finite(s.maxOrderAgeMs,this.settings.maxOrderAgeMs)),dailyLossLimitUsdt:Math.max(.1,finite(s.dailyLossLimitUsdt,this.settings.dailyLossLimitUsdt)),maxLeverageForDualSide:Math.max(1,finite(s.maxLeverageForDualSide??s.maxDualSideLeverage,this.settings.maxLeverageForDualSide)),capitalUtilization:Math.max(.1,Math.min(1,finite(s.capitalUtilization,this.settings.capitalUtilization))),requestedLeverage:Math.max(1,Math.min(100,finite(s.requestedLeverage,this.settings.requestedLeverage)))};return this.settings;}
  async reloadCredential(){const c=this.credentialStore.load();if(!c){this.client=null;this.privateWs=false;this.state='DISARMED';this.reason='CREDENTIAL_NOT_PROVISIONED';return this.status();}this.client=new ToobitDirectClient(c);await this.#refreshAccount();await this.#connectPrivate();return this.status();}
  async bindCredential({apiKey,secret,tradeStatus='DECLARED_UNVERIFIED'}={}){const probe=new ToobitDirectClient({apiKey,secret});await Promise.all([probe.balance(),probe.positions(this.symbol),probe.openOrders(this.symbol)]);this.credentialStore.save({apiKey,secret,tradeStatus,boundAt:new Date().toISOString()});return this.reloadCredential();}
  async deleteCredential(){await this.stop('CREDENTIAL_REMOVED');this.credentialStore.delete();this.client=null;this.privateWs=false;this.reason='CREDENTIAL_NOT_PROVISIONED';return this.status();}
  capability(){const cs=this.credentialStore.status();if(!cs.bound)return{ok:false,reason:'CREDENTIAL_NOT_PROVISIONED'};if(!this.liveEnabled)return{ok:false,reason:'LIVE_DISABLED'};if(!['VERIFIED','DECLARED_UNVERIFIED'].includes(cs.tradeStatus))return{ok:false,reason:'TRADE_NOT_DECLARED'};if(!this.publicWs)return{ok:false,reason:'PUBLIC_WS_OFFLINE'};if(!this.privateWs)return{ok:false,reason:'PRIVATE_WS_OFFLINE'};const snap=this.market.snapshot();if(snap.marketDataAgeMs>2000)return{ok:false,reason:'MARKET_STALE'};return{ok:true,reason:cs.tradeStatus==='VERIFIED'?'READY':'READY_TRADE_UNVERIFIED'};}
  async start(settings={}){this.setSettings(settings);const cap=this.capability();if(!cap.ok){this.state='DISARMED';this.reason=cap.reason;return this.status();}await this.#refreshAccount();await this.#reconcile();this.started=true;const inv=inventorySnapshot(this.account.positions),policy=this.#policy(inv),risk=evaluateRisk(this.#riskContext(policy),this.settings);if(!risk.ok)return this.stop(risk.reason);this.state=risk.state;this.reason=risk.reason;await this.quoteRunner.trigger();return this.status();}
  async stop(reason='MANUAL_DISARM'){this.started=false;this.lastStopReason=reason;try{await this.#cancelOwned();}catch(e){this.#recordError(e);}this.state='DISARMED';this.reason=reason;return this.status();}
  async pause(){this.started=false;try{await this.#cancelOwned();}catch(e){this.#recordError(e);}this.state='PAUSED';this.reason='MANUAL_PAUSE';return this.status();}
  async resume(settings={}){return this.start(settings);}
  status(){const inv=inventorySnapshot(this.account.positions),policy=this.#policy(inv),cs=this.credentialStore.status(),m=this.market.snapshot(),cap=this.capability();return{executorMode:'V49_LIVE',liveEnabled:this.liveEnabled,credentialBound:cs.bound,maskedKey:cs.maskedKey,tradePermissionStatus:cs.tradeStatus,publicWs:this.publicWs,privateWs:this.privateWs,state:this.state,reason:this.reason,lastStopReason:this.lastStopReason,lastError:this.lastError,apiErrorStreak:this.apiErrorStreak,quoteCycles:this.quoteRunner.runCount,quoteInFlight:this.quoteRunner.inFlight,capability:cap,marketDataAgeMs:m.marketDataAgeMs,fairPrice:this.lastFair,inventory:inv,inventoryPolicy:policy,openBotOrders:Number(Boolean(this.orders.bid))+Number(Boolean(this.orders.ask)),orders:{bid:this.orders.bid,ask:this.orders.ask},account:{balance:this.account.balance,available:this.account.available,todayPnl:this.account.todayPnl,positions:this.account.positions}};}
  async openBotOrders(){if(!this.client)return[];return normOrders(await this.client.openOrders(this.symbol)).filter(o=>o.clientOrderId.startsWith(this.prefix));}
  async #loadMarketSpec(){try{const r=await fetch('https://api.toobit.com/api/v1/exchangeInfo',{cache:'no-store'}),d=await r.json(),c=(d.contracts??[]).find(x=>x.symbol===this.symbol),f=(c?.filters??[]).find(x=>x.filterType==='PRICE_FILTER');this.tickSize=Math.max(.00000001,finite(f?.tickSize,.1));}catch{this.tickSize=.1;}}
  #connectPublic(){try{this.publicSocket?.close();}catch{}const ws=new WebSocket('wss://stream.toobit.com/quote/ws/v1');this.publicSocket=ws;ws.onopen=()=>{this.publicWs=true;ws.send(JSON.stringify({symbol:this.symbol,topic:'bookTicker',event:'sub'}));ws.send(JSON.stringify({symbol:this.symbol,topic:'diffDepth',event:'sub',params:{binary:false}}));};ws.onmessage=e=>{let m;try{m=JSON.parse(String(e.data));}catch{return;}const now=Date.now();let changed=false;if(m?.topic==='bookTicker'||m?.data?.e==='bookTicker')changed=this.market.onBookTicker(m,now);else if(m?.topic==='diffDepth')changed=this.market.onDiffDepth(m,now);if(changed&&this.started)this.quoteRunner.trigger().catch(e=>this.#recordError(e));};ws.onclose=()=>{this.publicWs=false;if(this.started)this.stop('PUBLIC_WS_OFFLINE').catch(()=>{});setTimeout(()=>this.#connectPublic(),1500);};ws.onerror=()=>{this.publicWs=false;};}
  async #connectPrivate(){if(!this.client)return;try{try{this.privateSocket?.close();}catch{}const lk=await this.client.createListenKey();this.listenKey=String(lk?.listenKey??first(lk)?.listenKey??'');if(!this.listenKey)throw new Error('LISTEN_KEY_EMPTY');const ws=new WebSocket(`wss://stream.toobit.com/api/v1/ws/${encodeURIComponent(this.listenKey)}`);this.privateSocket=ws;ws.onopen=()=>{this.privateWs=true;};ws.onmessage=e=>{let m;try{m=JSON.parse(String(e.data));}catch{return;}const events=Array.isArray(m)?m:[m];if(events.some(x=>/contractExecutionReport/i.test(String(x?.e??x?.eventType??'')))){this.privateRefreshPending=true;this.quoteRunner.trigger().catch(err=>this.#recordError(err));}};ws.onclose=()=>{this.privateWs=false;if(this.started)this.stop('PRIVATE_WS_OFFLINE').catch(()=>{});if(this.client)setTimeout(()=>this.#connectPrivate().catch(()=>{}),1500);};ws.onerror=()=>{this.privateWs=false;};}catch(e){this.privateWs=false;this.reason='PRIVATE_WS_OFFLINE';this.#recordError(e);setTimeout(()=>this.#connectPrivate().catch(()=>{}),5000);}}
  async #keepalive(){if(this.client&&this.listenKey)await this.client.keepaliveListenKey(this.listenKey);}
  async #refreshAccount(){if(!this.client)return;try{const [bal,pos,pnl,fee]=await Promise.all([this.client.balance(),this.client.positions(this.symbol),this.client.todayPnl(),this.client.commission(this.symbol)]);const b=rows(bal).find(x=>String(x.coin??'').toUpperCase()==='USDT')??first(bal);this.account.balance=finite(b?.balance);this.account.available=finite(b?.availableBalance);this.account.positions=normPositions(pos);this.account.todayPnl=finite(first(pnl)?.dayProfit??pnl?.dayProfit);const fr=first(fee);this.account.feeBps=Math.abs(finite(fr?.openMakerFee))*10000;this.apiErrorStreak=0;}catch(e){this.apiErrorStreak+=1;this.#recordError(e);throw e;}}
  #policy(inv){const lev=Math.max(1,this.settings.requestedLeverage),budget=Math.max(this.settings.quoteNotional*3,this.account.balance*this.settings.capitalUtilization*Math.min(lev,20)*.25);return inventoryPolicy(inv,{hardInventoryUsdt:budget,softInventoryUsdt:budget*.6,maxLeverageForDualSide:this.settings.maxLeverageForDualSide});}
  #riskContext(policy){const p=this.account.positions,riskRate=Math.max(0,...p.map(x=>finite(x.riskRate)));return{publicWs:this.publicWs,privateWs:this.privateWs,marketDataAgeMs:this.market.snapshot().marketDataAgeMs,apiErrorStreak:this.apiErrorStreak,dailyPnl:this.account.todayPnl,riskRate,inventoryPolicy:policy};}
  async #reconcile(){const all=normOrders(await this.client.openOrders(this.symbol)),owned=all.filter(o=>o.clientOrderId.startsWith(this.prefix));const pick=async(list)=>{const sorted=[...list].sort((x,y)=>finite(y.createdAt)-finite(x.createdAt));const keep=sorted[0]??null;for(const extra of sorted.slice(1)){try{await this.client.cancel(extra.clientOrderId);}catch(e){this.#recordError(e);}}return keep;};this.orders.bid=await pick(owned.filter(o=>o.side==='BUY'));this.orders.ask=await pick(owned.filter(o=>o.side==='SELL'));return{owned:owned.length,manual:all.length-owned.length};}
  async #quoteOnce(){if(!this.client)return;if(this.privateRefreshPending){this.privateRefreshPending=false;await this.#refreshAccount();await this.#reconcile();}if(!this.started)return;const inv=inventorySnapshot(this.account.positions),policy=this.#policy(inv),risk=evaluateRisk(this.#riskContext(policy),this.settings);if(!risk.ok)return this.stop(risk.reason);this.state=risk.state;this.reason=risk.reason;const m=this.market.snapshot(),fair=fairPrice(m,m.depthImbalance,2);if(!(fair>0))return;this.lastFair=fair;const desired=buildDesiredQuotes({market:m,fair,inventory:{...policy,allowBid:risk.allowBid&&policy.allowBid,allowAsk:risk.allowAsk&&policy.allowAsk},config:this.settings,tickSize:this.tickSize,feeBps:this.account.feeBps||1.2,adverseSelectionBps:1});if(desired.bid)desired.bid.positionSide=policy.reduceOnly?'SHORT':'LONG';if(desired.ask)desired.ask.positionSide=policy.reduceOnly?'LONG':'SHORT';this.lastDesired=desired;try{await this.#applySide('bid',desired.bid);await this.#applySide('ask',desired.ask);this.apiErrorStreak=0;}catch(e){this.#recordError(e);if(Number(e?.code)===-1158){await this.#reconcile().catch(()=>{});return;}this.apiErrorStreak+=1;if(this.apiErrorStreak>=3)await this.stop('API_ERROR_STREAK');throw e;}}
  async #applySide(key,target){const cur=this.orders[key],now=Date.now();if(!target){if(cur){try{await this.client.cancel(cur.clientOrderId);this.orders[key]=null;}catch(e){await this.#reconcile();if(this.orders[key])throw e;}}return;}if(!cur){const id=`${this.prefix}${now}_${crypto.randomBytes(3).toString('hex')}`,req={symbol:this.symbol,clientOrderId:id,side:target.side,positionSide:target.positionSide,valueQuantity:Number(target.notional).toFixed(2),price:target.price};const o=await this.client.place(req);this.credentialStore.markTradeVerified();const od=first(o),status=String(od?.status??'').toUpperCase();if(!isLiveStatus(status)){this.orders[key]=null;if(status==='FILLED'){this.privateRefreshPending=true;this.quoteRunner.pending=true;}else if(status)this.lastError=`ORDER_${status}`;return;}this.orders[key]={...req,...od,clientOrderId:String(od?.clientOrderId??id),price:finite(od?.price??target.price),status:status||'NEW',createdAt:now};return;}if(!shouldRequote(cur,target,now,this.settings,this.tickSize))return;const req={origClientOrderId:cur.clientOrderId,clientOrderId:cur.clientOrderId,valueQuantity:Number(target.notional).toFixed(2),price:target.price};try{const o=await this.client.update(req),od=first(o),status=String(od?.status??cur.status??'').toUpperCase();if(!isLiveStatus(status)){this.orders[key]=null;this.privateRefreshPending=true;this.quoteRunner.pending=true;return;}this.orders[key]={...cur,...od,price:finite(od?.price??target.price),status:status||cur.status,createdAt:now};}catch(e){await this.#reconcile();if(this.orders[key])throw e;}}
  async #cancelOwned(){if(!this.client)return;await this.#reconcile().catch(()=>{});for(const key of ['bid','ask']){const o=this.orders[key];if(o?.clientOrderId?.startsWith(this.prefix)){try{await this.client.cancel(o.clientOrderId);}catch(e){this.#recordError(e);}this.orders[key]=null;}}}
  async #watchdog(){if(!this.started)return;const inv=inventorySnapshot(this.account.positions),policy=this.#policy(inv),risk=evaluateRisk(this.#riskContext(policy),this.settings);if(!risk.ok)await this.stop(risk.reason);}
  #recordError(e){this.lastError=`${e?.code??''}${e?.code?' ':''}${String(e?.message??e??'').slice(0,180)}`.trim();}
}
