import { createClient } from 'npm:@supabase/supabase-js@2.57.4';

const OWNER = 'primary-admin';
const GATEWAY = 'tokyo-gateway';
const EXCHANGE = 'toobit';
const SYMBOL = 'BTC-SWAP-USDT';
const BASE = 'https://api.toobit.com';
const BOT_PREFIX = 'DKV48M_';
const MIN_NOTIONAL = 5;
const MAX_NOTIONAL = 20;

const secretMap = (() => { try { return JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS') || '{}'); } catch { return {}; } })();
const adminKey = (secretMap.default && Deno.env.get(secretMap.default)) || Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || '';
const supabase = createClient(Deno.env.get('SUPABASE_URL') || 'https://txutcpmarsvsdcvgyhtu.supabase.co', adminKey, { auth: { persistSession: false, autoRefreshToken: false } });
const te = new TextEncoder();
const td = new TextDecoder();
function json(status: number, data: unknown) { return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', 'x-content-type-options': 'nosniff' } }); }
async function sha256(s: string) { const d = new Uint8Array(await crypto.subtle.digest('SHA-256', te.encode(s))); return [...d].map((x) => x.toString(16).padStart(2, '0')).join(''); }
async function authed(req: Request) { const token = (req.headers.get('authorization') || '').replace(/^Bearer\s+/i, ''); if (!token) return false; const { data, error } = await supabase.from('gateway_auth').select('token_sha256').eq('owner_id', OWNER).eq('gateway_name', GATEWAY).maybeSingle(); return !error && !!data && (await sha256(token)) === String(data.token_sha256); }
function unb64(s: string) { const bin = atob(s); const out = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i); return out; }
async function controlSecret(name: string) { const { data, error } = await supabase.rpc('dkivn_get_control_secret', { p_name: name }); if (error || !data) throw new Error('CONTROL_SECRET_UNAVAILABLE'); return String(data); }
async function decryptPayload(masterB64: string, encoded: string) { const p = JSON.parse(String(encoded)); if (p.v !== 1) throw new Error('VAULT_VERSION'); const raw = unb64(masterB64); if (raw.length !== 32) throw new Error('MASTER_KEY_LENGTH'); const key = await crypto.subtle.importKey('raw', raw, 'AES-GCM', false, ['decrypt']); const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: unb64(p.iv) }, key, unb64(p.cipher)); return JSON.parse(td.decode(plain)); }
async function getCred() { const { data, error } = await supabase.from('exchange_credentials').select('encrypted_payload,key_last4,read_verified,trade_permission_status').eq('owner_id', OWNER).eq('exchange', EXCHANGE).maybeSingle(); if (error) throw error; if (!data) return null; const clear = await decryptPayload(await controlSecret('dkivn_credential_master_key'), String(data.encrypted_payload)); return { apiKey: String(clear.apiKey || ''), secret: String(clear.secret || ''), meta: data }; }
function enc(entries: [string, string][]) { return entries.map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`).join('&'); }
async function hmacHex(secret: string, text: string) { const key = await crypto.subtle.importKey('raw', te.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']); const sig = new Uint8Array(await crypto.subtle.sign('HMAC', key, te.encode(text))); return [...sig].map((b) => b.toString(16).padStart(2, '0')).join(''); }
async function signedQuery(path: string, method: string, c: any, extra: [string, string][] = []) { const q = enc([...extra, ['timestamp', String(Date.now())], ['recvWindow', '5000']]); const sig = await hmacHex(c.secret, q); const ctl = new AbortController(); const timer = setTimeout(() => ctl.abort(), 7000); const started = Date.now(); try { const r = await fetch(`${BASE}${path}?${q}&signature=${sig}`, { method, headers: { 'X-BB-APIKEY': c.apiKey, Accept: 'application/json' }, cache: 'no-store', signal: ctl.signal }); const text = await r.text(); let data: any; try { data = JSON.parse(text); } catch { data = { message: 'NON_JSON' }; } return { ok: r.ok, status: r.status, elapsed: Date.now() - started, data, rate: { status: r.headers.get('x-api-limit-status'), limit: r.headers.get('x-api-limit'), reset: r.headers.get('x-api-limit-reset-timestamp') } }; } finally { clearTimeout(timer); } }
async function signedForm(path: string, method: string, c: any, payload: Record<string, unknown>) { const entries: [string, string][] = Object.entries(payload).filter(([, v]) => v !== undefined && v !== null).map(([k, v]) => [k, String(v)]); const unsigned = enc([...entries, ['timestamp', String(Date.now())], ['recvWindow', '5000']]); const signature = await hmacHex(c.secret, unsigned); const body = `${unsigned}&signature=${signature}`; const ctl = new AbortController(); const timer = setTimeout(() => ctl.abort(), 7000); const started = Date.now(); try { const r = await fetch(`${BASE}${path}`, { method, headers: { 'X-BB-APIKEY': c.apiKey, Accept: 'application/json', 'Content-Type': 'application/x-www-form-urlencoded' }, body, cache: 'no-store', signal: ctl.signal }); const text = await r.text(); let data: any; try { data = JSON.parse(text); } catch { data = { message: 'NON_JSON' }; } return { ok: r.ok, status: r.status, elapsed: Date.now() - started, data }; } finally { clearTimeout(timer); } }
function rows(data: any) { return Array.isArray(data) ? data : Array.isArray(data?.data) ? data.data : []; }
function codeOk(r: any) { if (!r?.ok) return false; const c = Number(r.data?.code ?? 200); return !Number.isFinite(c) || c === 0 || c === 200; }
function n(v: any) { const x = Number(v); return Number.isFinite(x) ? x : 0; }
function safeOrder(o: any) { return { orderId: String(o?.orderId ?? ''), clientOrderId: String(o?.clientOrderId ?? ''), symbol: String(o?.symbol ?? ''), side: String(o?.side ?? '').toUpperCase(), positionSide: String(o?.positionSide ?? '').toUpperCase(), status: String(o?.status ?? ''), price: n(o?.price), origQty: n(o?.origQty), executedQty: n(o?.executedQty), avgPrice: n(o?.avgPrice), timeInForce: String(o?.timeInForce ?? ''), time: n(o?.time), updateTime: n(o?.updateTime) }; }
function safePosition(p: any) { return { symbol: String(p?.symbol ?? ''), side: String(p?.side ?? p?.positionSide ?? '').toUpperCase(), position: n(p?.position), available: n(p?.available), positionValue: Math.abs(n(p?.positionValue)), avgPrice: n(p?.avgPrice), riskRate: n(p?.riskRate ?? p?.rr), unrealizedPnl: n(p?.unrealizedPnL), realizedPnl: n(p?.realizedPnL), liquidationPrice: n(p?.flp), leverage: n(p?.leverage) }; }
async function accountCore(c: any) { const [bal, pos] = await Promise.all([signedQuery('/api/v1/futures/balance', 'GET', c), signedQuery('/api/v1/futures/positions', 'GET', c, [['symbol', SYMBOL]])]); if (!codeOk(bal) || !codeOk(pos)) throw new Error('ACCOUNT_CORE_FAILED'); const balances = rows(bal.data); const b = balances.find((x: any) => String(x?.coin || '').toUpperCase() === 'USDT') || balances[0] || {}; const positions = rows(pos.data).map(safePosition).filter((p: any) => p.symbol === SYMBOL); const active = positions.find((p: any) => Math.abs(p.position) > 0) || positions[0] || safePosition({}); return { balance: { balance: n(b.balance), availableBalance: n(b.availableBalance) }, position: active, positions }; }
async function botOpenOrders(c: any) { const r = await signedQuery('/api/v2/futures/open-orders', 'GET', c, [['symbol', SYMBOL], ['limit', '1000'], ['category', 'USDT']]); if (!codeOk(r)) throw new Error('OPEN_ORDERS_FAILED'); return rows(r.data).map(safeOrder).filter((o: any) => o.clientOrderId.startsWith(BOT_PREFIX)); }
async function cancelBotOrder(c: any, cid: string) { if (!cid.startsWith(BOT_PREFIX)) throw new Error('INVALID_BOT_CLIENT_ID'); return signedQuery('/api/v2/futures/order', 'DELETE', c, [['origClientOrderId', cid], ['category', 'USDT']]); }
function validateMakerBody(b: any) { const side = String(b.side || '').toUpperCase(); const positionSide = String(b.positionSide || '').toUpperCase(); const cid = String(b.clientOrderId || ''); const price = n(b.price); const value = n(b.valueQuantity); if (!['BUY', 'SELL'].includes(side) || !['LONG', 'SHORT'].includes(positionSide) || !cid.startsWith(BOT_PREFIX) || !(price > 0) || !(value >= MIN_NOTIONAL && value <= MAX_NOTIONAL)) throw new Error('INVALID_MAKER_ORDER'); return { side, positionSide, cid, price, value }; }
function selfCrosses(open: any[], side: string, price: number, ignoreCid = '') { return open.some((o) => o.clientOrderId !== ignoreCid && ((side === 'BUY' && o.side === 'SELL' && price >= o.price) || (side === 'SELL' && o.side === 'BUY' && price <= o.price))); }
async function persistAcceptedOrder(order: any, value: number, strategy: string) { const row = { owner_id: OWNER, exchange: EXCHANGE, symbol: SYMBOL, client_order_id: order.clientOrderId, exchange_order_id: String(order.orderId ?? ''), side: order.side, position_side: order.positionSide, status: String(order.status ?? 'NEW'), requested_notional: value, price: n(order.price), raw_safe: { status: order.status ?? 'NEW', timeInForce: 'POST_ONLY', strategy } }; await supabase.from('bot_orders').upsert(row, { onConflict: 'owner_id,client_order_id' }); }

Deno.serve(async (req) => {
  try {
    if (!(await authed(req))) return json(401, { ok: false, error: 'UNAUTHORIZED' });
    const u = new URL(req.url); const path = u.pathname.split('/dkivn-v47-gateway-telemetry')[1] || '/';
    if (path === '/health' && req.method === 'GET') return json(200, { ok: true, service: 'dkivn-v47-gateway-telemetry', version: 8, maker: true, strategy: 'V48_ADAPTIVE_MAKER', orderWire: 'FORM_URLENCODED', botPrefix: BOT_PREFIX });
    if (path === '/listen-key' && ['POST', 'PUT', 'DELETE'].includes(req.method)) { const c = await getCred(); if (!c?.apiKey || !c?.secret) return json(409, { ok: false, error: 'TOOBIT_CREDENTIAL_NOT_BOUND' }); const b = await req.json().catch(() => ({})); const extra: [string, string][] = [['category', 'USDT']]; if (req.method !== 'POST') { const lk = String(b.listenKey || ''); if (!lk) return json(400, { ok: false, error: 'LISTEN_KEY_REQUIRED' }); extra.unshift(['listenKey', lk]); } const r = await signedQuery('/api/v1/listenKey', req.method, c, extra); if (!codeOk(r)) return json(502, { ok: false, error: 'LISTEN_KEY_UPSTREAM_FAILED', status: r.status, code: r.data?.code ?? null, message: String(r.data?.msg ?? r.data?.message ?? 'Toobit rejected listenKey request').slice(0, 180) }); const lk = String(r.data?.listenKey ?? r.data?.data?.listenKey ?? b.listenKey ?? ''); return json(200, { ok: true, listenKey: lk, expiresAt: Date.now() + 60 * 60 * 1000, latencyMs: r.elapsed }); }
    if (path === '/account-snapshot' && req.method === 'GET') { const c = await getCred(); if (!c) return json(409, { ok: false, error: 'TOOBIT_CREDENTIAL_NOT_BOUND' }); const [core, pnl, ord] = await Promise.all([accountCore(c), signedQuery('/api/v1/futures/todayPnl', 'GET', c, [['category', 'USDT']]), signedQuery('/api/v2/futures/open-orders', 'GET', c, [['symbol', SYMBOL], ['limit', '1000'], ['category', 'USDT']])]); if (!codeOk(pnl) || !codeOk(ord)) return json(502, { ok: false, error: 'ACCOUNT_SNAPSHOT_FAILED' }); const bot = rows(ord.data).filter((x: any) => String(x?.clientOrderId || '').startsWith(BOT_PREFIX)); return json(200, { ok: true, balance: core.balance, position: core.position, positions: core.positions, todayPnl: n(pnl.data?.dayProfit ?? pnl.data?.data?.dayProfit), openBotOrders: bot.length, apiLimit: ord.rate }); }
    if (path === '/maker/open-orders' && req.method === 'GET') { const c = await getCred(); if (!c) return json(409, { ok: false, error: 'TOOBIT_CREDENTIAL_NOT_BOUND' }); return json(200, { ok: true, orders: await botOpenOrders(c) }); }
    if (path === '/maker/place' && req.method === 'POST') { const c = await getCred(); if (!c) return json(409, { ok: false, error: 'TOOBIT_CREDENTIAL_NOT_BOUND' }); let parsed; try { parsed = validateMakerBody(await req.json().catch(() => ({}))); } catch { return json(400, { ok: false, error: 'INVALID_MAKER_ORDER' }); } const { side, positionSide, cid, price, value } = parsed; const open = await botOpenOrders(c); if (open.some((o: any) => o.side === side)) return json(409, { ok: false, error: 'BOT_SIDE_ALREADY_OPEN' }); if (selfCrosses(open, side, price)) return json(409, { ok: false, error: 'SELF_CROSS_GUARD' }); const payload = { symbol: SYMBOL, side, positionSide, type: 'LIMIT', newClientOrderId: cid, valueQuantity: value.toFixed(2), price: String(price), timeInForce: 'POST_ONLY', category: 'USDT' }; const r = await signedForm('/api/v2/futures/order', 'POST', c, payload); if (!codeOk(r)) return json(502, { ok: false, error: 'TOOBIT_ORDER_REJECTED', status: r.status, code: r.data?.code ?? null, message: String(r.data?.msg ?? r.data?.message ?? 'Order rejected').slice(0, 180) }); const od = safeOrder(r.data?.data ?? r.data); if (!od.clientOrderId) od.clientOrderId = cid; od.side = side; od.positionSide = positionSide; od.price = price; await supabase.from('exchange_credentials').update({ trade_permission_status: 'VERIFIED', updated_at: new Date().toISOString() }).eq('owner_id', OWNER).eq('exchange', EXCHANGE); await persistAcceptedOrder(od, value, 'V48_ADAPTIVE_MAKER'); return json(200, { ok: true, order: od, latencyMs: r.elapsed }); }
    if (path === '/maker/update' && req.method === 'POST') { const c = await getCred(); if (!c) return json(409, { ok: false, error: 'TOOBIT_CREDENTIAL_NOT_BOUND' }); const b = await req.json().catch(() => ({})); const cid = String(b.clientOrderId ?? b.origClientOrderId ?? ''); const price = n(b.price); const value = n(b.valueQuantity); if (!cid.startsWith(BOT_PREFIX) || !(price > 0) || !(value >= MIN_NOTIONAL && value <= MAX_NOTIONAL)) return json(400, { ok: false, error: 'INVALID_MAKER_UPDATE' }); const open = await botOpenOrders(c); const current = open.find((o: any) => o.clientOrderId === cid); if (!current) return json(404, { ok: false, error: 'BOT_ORDER_NOT_FOUND' }); if (selfCrosses(open, current.side, price, cid)) return json(409, { ok: false, error: 'SELF_CROSS_GUARD' }); const r = await signedForm('/api/v2/futures/order/update', 'POST', c, { origClientOrderId: cid, valueQuantity: value.toFixed(2), price: String(price), category: 'USDT' }); if (!codeOk(r)) return json(502, { ok: false, error: 'TOOBIT_UPDATE_REJECTED', status: r.status, code: r.data?.code ?? null, message: String(r.data?.msg ?? r.data?.message ?? 'Update rejected').slice(0, 180) }); const od = safeOrder(r.data?.data ?? r.data); if (!od.clientOrderId) od.clientOrderId = cid; await supabase.from('bot_orders').update({ price, requested_notional: value, status: String(od.status || 'NEW'), updated_at: new Date().toISOString() }).eq('owner_id', OWNER).eq('client_order_id', cid); return json(200, { ok: true, order: od, latencyMs: r.elapsed }); }
    if (path === '/maker/cancel' && req.method === 'POST') { const c = await getCred(); if (!c) return json(409, { ok: false, error: 'TOOBIT_CREDENTIAL_NOT_BOUND' }); const b = await req.json().catch(() => ({})); const cid = String(b.clientOrderId || ''); if (!cid.startsWith(BOT_PREFIX)) return json(400, { ok: false, error: 'INVALID_BOT_CLIENT_ID' }); const r = await cancelBotOrder(c, cid); if (!codeOk(r)) return json(502, { ok: false, error: 'ORDER_CANCEL_FAILED', code: r.data?.code ?? null, message: String(r.data?.msg ?? r.data?.message ?? 'cancel failed').slice(0, 180) }); await supabase.from('bot_orders').update({ status: 'CANCELED', updated_at: new Date().toISOString() }).eq('owner_id', OWNER).eq('client_order_id', cid); return json(200, { ok: true, canceled: true, clientOrderId: cid }); }
    if (path === '/maker/cancel-all' && req.method === 'POST') { const c = await getCred(); if (!c) return json(409, { ok: false, error: 'TOOBIT_CREDENTIAL_NOT_BOUND' }); const open = await botOpenOrders(c); let canceled = 0; const errors: any[] = []; for (const o of open) { const r = await cancelBotOrder(c, o.clientOrderId); if (codeOk(r)) { canceled += 1; await supabase.from('bot_orders').update({ status: 'CANCELED', updated_at: new Date().toISOString() }).eq('owner_id', OWNER).eq('client_order_id', o.clientOrderId); } else errors.push({ clientOrderId: o.clientOrderId, code: r.data?.code ?? r.status }); } return json(errors.length ? 207 : 200, { ok: errors.length === 0, canceled, errors }); }
    if (path === '/command' && req.method === 'GET') { const { data, error } = await supabase.from('bot_commands').select('id,action,requested_at').eq('owner_id', OWNER).eq('exchange', EXCHANGE).eq('symbol', SYMBOL).is('acknowledged_at', null).order('requested_at', { ascending: true }).limit(1).maybeSingle(); if (error) return json(502, { ok: false, error: 'COMMAND_READ_FAILED' }); return json(200, { ok: true, command: data || null }); }
    if (path === '/ack' && req.method === 'POST') { const b = await req.json().catch(() => ({})); const id = Number(b.id); if (!Number.isFinite(id)) return json(400, { ok: false, error: 'INVALID_ID' }); const { error } = await supabase.from('bot_commands').update({ acknowledged_at: new Date().toISOString(), acknowledged_state: String(b.state || 'UNKNOWN') }).eq('id', id).eq('owner_id', OWNER); if (error) return json(502, { ok: false, error: 'ACK_FAILED' }); return json(200, { ok: true }); }
    if (path === '/telemetry' && req.method === 'POST') { const b = await req.json().catch(() => ({})); const row = { ...b, owner_id: OWNER, exchange: EXCHANGE, symbol: SYMBOL, heartbeat_at: new Date().toISOString(), updated_at: new Date().toISOString() }; const { error } = await supabase.from('gateway_telemetry').upsert(row, { onConflict: 'owner_id,exchange' }); if (error) return json(502, { ok: false, error: 'TELEMETRY_WRITE_FAILED', message: error.message }); return json(200, { ok: true }); }
    if (path === '/runtime' && req.method === 'POST') { const b = await req.json().catch(() => ({})); const row = { ...b, owner_id: OWNER, exchange: EXCHANGE, symbol: SYMBOL, updated_at: new Date().toISOString() }; const { error } = await supabase.from('bot_runtime').upsert(row, { onConflict: 'owner_id,exchange' }); if (error) return json(502, { ok: false, error: 'RUNTIME_WRITE_FAILED', message: error.message }); return json(200, { ok: true }); }
    return json(404, { ok: false, error: 'NOT_FOUND' });
  } catch (e) { return json(500, { ok: false, error: 'INTERNAL', message: String((e as any)?.message || e).slice(0, 180) }); }
});
