import test from 'node:test';
import assert from 'node:assert/strict';
import { AdaptiveMakerGateway } from '../src/gateway.js';

class FakeExecutor { constructor(){this.calls=[];this.owned=[];} reconcile(o){this.calls.push(['reconcile',o]);this.owned=o;return {ownedCount:o.length,manualCount:0};} async applyDesiredQuotes(q,now){this.calls.push(['apply',q,now]);return {};} async cancelOwned(reason){this.calls.push(['cancelOwned',reason]);return {};} snapshot(){return {bid:null,ask:null,metrics:{amendCount:0,cancelCount:0,createCount:0}};} }
class FakeAccount { constructor(){this.calls=[];this.data={positions:[],todayPnl:0,position:{riskRate:0},balance:{availableBalance:100}};this.orders=[];} async snapshot(){this.calls.push('snapshot');return this.data;} async openOrders(){this.calls.push('openOrders');return this.orders;} }
function make({privateWs=true,publicWs=true}={}){const executor=new FakeExecutor(),account=new FakeAccount(),conn={publicWs,privateWs};const g=new AdaptiveMakerGateway({config:{symbol:'BTC-SWAP-USDT',botPrefix:'DKV48M_',quoteNotional:10,softInventoryUsdt:10,hardInventoryUsdt:20,minQuoteLifeMs:2500,requoteBps:2,marketStaleMs:2000,clockSkewHardMs:1500,apiErrorHardLimit:3,dailyLossLimitUsdt:2,riskHard:90,liveEnabled:true},executor,accountProvider:account,connectivity:()=>conn,clockSkewMs:()=>0,tickSize:0.1,feeBps:1.2,adverseSelectionBps:1});return {g,executor,account,conn};}
async function seed(g){await g.onBookTicker({data:{b:'100',a:'101',bq:'5',aq:'5'}},1000);await g.onDiffDepth({data:{b:[['100','5']],a:[['101','5']]}},1000);}

test('bookTicker price change triggers quote evaluation while running',async()=>{const {g,executor}=make();await seed(g);await g.handleCommand('START',1000);const before=executor.calls.filter(c=>c[0]==='apply').length;await g.onBookTicker({data:{b:'100.1',a:'101.1',bq:'5',aq:'5'}},1100);assert.ok(executor.calls.filter(c=>c[0]==='apply').length>before);});
test('meaningful depth imbalance change triggers quote evaluation',async()=>{const {g,executor}=make();await seed(g);await g.handleCommand('START',1000);const before=executor.calls.filter(c=>c[0]==='apply').length;await g.onDiffDepth({data:{b:[['100','20']],a:[['101','1']]}},1200);assert.ok(executor.calls.filter(c=>c[0]==='apply').length>before);});
test('unchanged market does not create a timer-driven quote loop',async()=>{const {g,executor}=make();await seed(g);await g.handleCommand('START',1000);const before=executor.calls.filter(c=>c[0]==='apply').length;await g.watchdog(1100);await g.watchdog(1200);assert.equal(executor.calls.filter(c=>c[0]==='apply').length,before);});
test('fill event reconciles and recalculates quotes',async()=>{const {g,executor,account}=make();await seed(g);await g.handleCommand('START',1000);const before=executor.calls.filter(c=>c[0]==='apply').length;account.orders=[{clientOrderId:'DKV48M_x',side:'BUY',price:100}];await g.onPrivateEvent({e:'executionReport',X:'FILLED'},1300);assert.ok(executor.calls.some(c=>c[0]==='reconcile'));assert.ok(executor.calls.filter(c=>c[0]==='apply').length>before);});
test('PAUSE cancels owned quotes and prevents new quote evaluation',async()=>{const {g,executor}=make();await seed(g);await g.handleCommand('START',1000);await g.handleCommand('PAUSE',1100);const before=executor.calls.filter(c=>c[0]==='apply').length;await g.onBookTicker({data:{b:'100.2',a:'101.2',bq:'5',aq:'5'}},1200);assert.ok(executor.calls.some(c=>c[0]==='cancelOwned'));assert.equal(executor.calls.filter(c=>c[0]==='apply').length,before);});
test('RESUME reconciles before returning RUNNING',async()=>{const {g,executor}=make();await seed(g);await g.handleCommand('START',1000);await g.handleCommand('PAUSE',1100);executor.calls=[];const r=await g.handleCommand('RESUME',1200);assert.equal(executor.calls[0][0],'reconcile');assert.equal(r.state,'RUNNING');});
test('START stays DISARMED when readiness fails',async()=>{const {g,executor}=make({privateWs:false});await seed(g);const r=await g.handleCommand('START',1000);assert.equal(r.state,'DISARMED');assert.equal(r.reason,'PRIVATE_WS_OFFLINE');assert.equal(executor.calls.some(c=>c[0]==='apply'),false);});
