import { pathToFileURL } from 'node:url';
import { loadConfig } from './config.js';
import { MarketDataEngine } from './market-data.js';
import { microPrice, fairPrice, RollingVolatility } from './fair-value.js';
import { inventorySnapshot, inventoryPolicy } from './inventory.js';
import { buildDesiredQuotes } from './quote-engine.js';
import { OrderExecutor } from './order-executor.js';
import { evaluateReadiness, evaluateRuntimeRisk } from './risk-engine.js';

const finite = (v, fallback = 0) => Number.isFinite(Number(v)) ? Number(v) : fallback;
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export class AdaptiveMakerGateway {
  constructor({config=loadConfig(),executor,accountProvider,marketData=new MarketDataEngine(config.symbol),connectivity=()=>({publicWs:false,privateWs:false}),clockSkewMs=()=>0,tickSize=0.1,feeBps=1.2,adverseSelectionBps=1,imbalanceBps=2,depthTrigger=0.05}={}) {
    if (!executor || !accountProvider) throw new Error('GATEWAY_DEPENDENCY_REQUIRED');
    Object.assign(this,{config,executor,accountProvider,marketData,connectivity,clockSkewMs,tickSize,feeBps,adverseSelectionBps,imbalanceBps,depthTrigger});
    this.volatility=new RollingVolatility(30);this.state='DISARMED';this.reason='STARTUP_SAFE';this.account={positions:[],todayPnl:0,position:{riskRate:0},balance:{availableBalance:0}};this.apiErrorStreak=0;this.reconciliationAmbiguous=false;this.selfCrossGuardFailed=false;this.lastDepthImbalance=null;this.lastFair=null;this.lastMicro=null;this.lastDesired={bid:null,ask:null,minEdgeBps:0};this.lastReject={code:null,message:null,at:null};this.fillCount=0;this.makerFillCount=0;
  }
  async onBookTicker(payload,recvMs=Date.now()){const before=this.marketData.snapshot(recvMs);const valid=this.marketData.onBookTicker(payload,recvMs);if(!valid)return false;const after=this.marketData.snapshot(recvMs);if(after.midPrice)this.volatility.push(after.midPrice);const changed=before.bestBid!==after.bestBid||before.bestAsk!==after.bestAsk||before.bestBidQty!==after.bestBidQty||before.bestAskQty!==after.bestAskQty;if((this.state==='RUNNING'||this.state==='RISK_REDUCE')&&changed)await this.#evaluateQuotes(recvMs);return true;}
  async onDiffDepth(payload,recvMs=Date.now()){const before=this.marketData.snapshot(recvMs);const valid=this.marketData.onDiffDepth(payload,recvMs);if(!valid)return false;const after=this.marketData.snapshot(recvMs);const delta=Math.abs((after.depthImbalance??0)-(before.depthImbalance??0));this.lastDepthImbalance=after.depthImbalance;if((this.state==='RUNNING'||this.state==='RISK_REDUCE')&&delta>=this.depthTrigger)await this.#evaluateQuotes(recvMs);return true;}
  async onPrivateEvent(event,recvMs=Date.now()){const type=String(event?.e??event?.eventType??event?.event??'').toLowerCase();const status=String(event?.X??event?.orderStatus??event?.status??'').toUpperCase();const relevant=/order|execution|trade|fill/.test(type)||['FILLED','PARTIALLY_FILLED','CANCELED','REJECTED'].includes(status);if(!relevant)return false;if(status==='FILLED'||status==='PARTIALLY_FILLED'||/trade|fill/.test(type)){this.fillCount+=1;if(event?.m===true||event?.isMaker===true)this.makerFillCount+=1;}await this.#reconcile();if(this.state==='RUNNING'||this.state==='RISK_REDUCE')await this.#evaluateQuotes(recvMs);return true;}
  async handleCommand(action,nowMs=Date.now()){const cmd=String(action||'').toUpperCase();if(cmd==='DISARM')return this.#disarm('MANUAL_DISARM');if(cmd==='PAUSE'){await this.executor.cancelOwned('MANUAL_PAUSE');this.state='PAUSED';this.reason='MANUAL_PAUSE';return this.status();}if(cmd==='START'||cmd==='RESUME')return this.#start(nowMs);return this.status();}
  async watchdog(nowMs=Date.now()){if(!['RUNNING','RISK_REDUCE'].includes(this.state))return this.status();const risk=evaluateRuntimeRisk(this.#riskContext(nowMs),this.config);if(!risk.ok)return this.#disarm(risk.reason);this.state=risk.state;this.reason=risk.reason;return this.status();}
  status(){return Object.freeze({state:this.state,reason:this.reason,apiErrorStreak:this.apiErrorStreak});}
  telemetrySnapshot(nowMs=Date.now()){const market=this.marketData.snapshot(nowMs);const inv=inventorySnapshot(this.account.positions??[]);const ex=this.executor.snapshot();const bid=ex.bid,ask=ex.ask,fair=this.lastFair;const grossEdge=bid&&ask&&fair?(ask.price-bid.price)/fair*10000:null;const netEdge=grossEdge==null?null:grossEdge-2*this.feeBps-this.adverseSelectionBps;return {strategy_mode:'V48_ADAPTIVE_MAKER',strategy_status:this.state,fair_price:this.lastFair,micro_price:this.lastMicro,depth_imbalance:market.depthImbalance,short_volatility:this.volatility.valueBps(),maker_bid_price:bid?.price??null,maker_ask_price:ask?.price??null,maker_bid_notional:bid?.valueQuantity??bid?.notional??null,maker_ask_notional:ask?.valueQuantity??ask?.notional??null,long_inventory_notional:inv.longInventoryNotional,short_inventory_notional:inv.shortInventoryNotional,net_inventory_notional:inv.netInventoryNotional,gross_inventory_notional:inv.grossInventoryNotional,quote_age_bid_ms:bid?Math.max(0,nowMs-finite(bid.createdAt,nowMs)):null,quote_age_ask_ms:ask?Math.max(0,nowMs-finite(ask.createdAt,nowMs)):null,fill_count:this.fillCount,maker_fill_count:this.makerFillCount,maker_fill_rate:this.fillCount?this.makerFillCount/this.fillCount:0,amend_count:ex.metrics?.amendCount??0,cancel_count:ex.metrics?.cancelCount??0,cancel_to_fill_ratio:this.fillCount?(ex.metrics?.cancelCount??0)/this.fillCount:0,estimated_adverse_selection_bps:this.adverseSelectionBps,estimated_net_edge_bps:netEdge,last_reject_code:this.lastReject.code,last_reject_message:this.lastReject.message,last_reject_at:this.lastReject.at,bid:market.bestBid,ask:market.bestAsk,mid:market.midPrice,public_ws_connected:Boolean(this.connectivity().publicWs),private_ws_connected:Boolean(this.connectivity().privateWs),open_bot_orders:Number(Boolean(bid))+Number(Boolean(ask)),inventory_value:inv.grossInventoryNotional,buy_quote_price:bid?.price??null,sell_quote_price:ask?.price??null,buy_quote_notional:bid?.valueQuantity??bid?.notional??null,sell_quote_notional:ask?.valueQuantity??ask?.notional??null,net_edge_bps:netEdge};}
  runtimeSnapshot(nowMs=Date.now()){const conn=this.connectivity(),market=this.marketData.snapshot(nowMs),inv=inventorySnapshot(this.account.positions??[]),ex=this.executor.snapshot();const riskRate=Math.max(...(this.account.positions??[]).map((p)=>finite(p.riskRate)),finite(this.account.position?.riskRate));return {state:this.state,reason:this.reason,manual_rearm_required:this.state==='DISARMED',public_ws_connected:Boolean(conn.publicWs),private_ws_connected:Boolean(conn.privateWs),last_market_at:Number.isFinite(market.marketDataAgeMs)?new Date(nowMs-market.marketDataAgeMs).toISOString():null,risk_rate:riskRate,daily_pnl:finite(this.account.todayPnl),unrealized_pnl:(this.account.positions??[]).reduce((s,p)=>s+finite(p.unrealizedPnl),0),realized_pnl:(this.account.positions??[]).reduce((s,p)=>s+finite(p.realizedPnl),0),position_value:inv.grossInventoryNotional,liquidation_price:finite(this.account.position?.liquidationPrice),open_bot_orders:Number(Boolean(ex.bid))+Number(Boolean(ex.ask)),api_error_streak:this.apiErrorStreak};}
  async #start(nowMs){try{await this.#reconcile();}catch(e){this.reconciliationAmbiguous=true;return this.#disarm('RECONCILIATION_AMBIGUOUS');}const ready=evaluateReadiness(this.#riskContext(nowMs),this.config);if(!ready.ok)return this.#disarm(ready.reason);this.state='READY';this.reason='READY';this.state='RUNNING';this.reason='MAKER_ACTIVE';await this.#evaluateQuotes(nowMs);return this.status();}
  async #reconcile(){this.account=await this.accountProvider.snapshot();const orders=await this.accountProvider.openOrders();this.executor.reconcile(orders);this.reconciliationAmbiguous=false;return true;}
  #riskContext(nowMs){const conn=this.connectivity(),market=this.marketData.snapshot(nowMs),inv=inventorySnapshot(this.account.positions??[]),policy=inventoryPolicy(inv,this.config);const riskRate=Math.max(...(this.account.positions??[]).map((p)=>finite(p.riskRate)),finite(this.account.position?.riskRate));return {publicWs:Boolean(conn.publicWs),privateWs:Boolean(conn.privateWs),marketDataAgeMs:market.marketDataAgeMs,clockSkewMs:finite(this.clockSkewMs()),reconciliationAmbiguous:this.reconciliationAmbiguous,selfCrossGuardFailed:this.selfCrossGuardFailed,apiErrorStreak:this.apiErrorStreak,dailyPnl:finite(this.account.todayPnl),riskRate,inventoryPolicy:policy,accountReady:Boolean(this.account)};}
  async #evaluateQuotes(nowMs){const risk=evaluateRuntimeRisk(this.#riskContext(nowMs),this.config);if(!risk.ok)return this.#disarm(risk.reason);this.state=risk.state;this.reason=risk.reason;const market=this.marketData.snapshot(nowMs),inv=inventorySnapshot(this.account.positions??[]),policy=inventoryPolicy(inv,this.config);try{this.lastMicro=microPrice(market);this.lastFair=fairPrice(market,market.depthImbalance,this.imbalanceBps);if(!(this.lastFair>0))throw new Error('FAIR_PRICE_UNAVAILABLE');const desired=buildDesiredQuotes({market,fair:this.lastFair,inventory:{...policy,allowBid:risk.allowBid&&policy.allowBid,allowAsk:risk.allowAsk&&policy.allowAsk},config:this.config,tickSize:this.tickSize,feeBps:this.feeBps,adverseSelectionBps:this.adverseSelectionBps});if(desired.bid)desired.bid.positionSide=inv.netInventoryNotional<0?'SHORT':'LONG';if(desired.ask)desired.ask.positionSide=inv.netInventoryNotional>0?'LONG':'SHORT';this.lastDesired=desired;await this.executor.applyDesiredQuotes(desired,nowMs);this.apiErrorStreak=0;this.selfCrossGuardFailed=false;}catch(e){const msg=String(e?.message||e);if(/SELF_CROSS/.test(msg)){this.selfCrossGuardFailed=true;return this.#disarm('SELF_CROSS_GUARD');}this.apiErrorStreak+=1;this.lastReject={code:e?.code??null,message:msg.slice(0,180),at:new Date(nowMs).toISOString()};if(this.apiErrorStreak>=this.config.apiErrorHardLimit)return this.#disarm('API_ERROR_STREAK');}return this.status();}
  async #disarm(reason){try{await this.executor.cancelOwned(reason);}catch{}this.state='DISARMED';this.reason=reason;return this.status();}
}

class BridgeClient{constructor(base,token){this.base=base;this.token=token;}async call(path,{method='GET',body}={}){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),7000);try{const r=await fetch(this.base+path,{method,headers:{Authorization:`Bearer ${this.token}`,Accept:'application/json',...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body!==undefined?JSON.stringify(body):undefined,cache:'no-store',signal:ctl.signal});const data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(`${path}:${r.status}:${data.error||data.message||'ERR'}`);e.code=data.code??r.status;throw e;}return data;}finally{clearTimeout(timer);}}}
class BridgeAccountProvider{constructor(bridge){this.bridge=bridge;}snapshot(){return this.bridge.call('/account-snapshot');}async openOrders(){return(await this.bridge.call('/maker/open-orders')).orders??[];}}
class BridgeOrderTransport{constructor(bridge){this.bridge=bridge;}async place(o){return(await this.bridge.call('/maker/place',{method:'POST',body:{side:o.side,positionSide:o.positionSide,clientOrderId:o.clientOrderId,price:o.price,valueQuantity:o.valueQuantity}})).order;}async update(o){return(await this.bridge.call('/maker/update',{method:'POST',body:{clientOrderId:o.origClientOrderId||o.clientOrderId,price:o.price,valueQuantity:o.valueQuantity}})).order;}async cancel(id){return this.bridge.call('/maker/cancel',{method:'POST',body:{clientOrderId:id}});}}
async function fetchTickSize(symbol){try{const r=await fetch('https://api.toobit.com/api/v1/exchangeInfo',{headers:{Accept:'application/json'},cache:'no-store'});const d=await r.json(),contracts=d?.contracts??[],c=contracts.find((x)=>x.symbol===symbol),f=c?.filters?.find((x)=>x.filterType==='PRICE_FILTER'),tick=finite(f?.tickSize);return tick>0?tick:0.1;}catch{return 0.1;}}
export async function runProduction(){const config=loadConfig(),bridgeUrl=process.env.DKIVN_BRIDGE_URL,token=process.env.DKIVN_GATEWAY_TOKEN;if(!bridgeUrl||!token)throw new Error('GATEWAY_ENV_MISSING');const bridge=new BridgeClient(bridgeUrl,token);await bridge.call('/health');const conn={publicWs:false,privateWs:false};let clockSkew=0,publicWs=null,privateWs=null,listenKey='',stopping=false;const tickSize=await fetchTickSize(config.symbol),marketData=new MarketDataEngine(config.symbol),accountProvider=new BridgeAccountProvider(bridge),executor=new OrderExecutor({transport:new BridgeOrderTransport(bridge),config,symbol:config.symbol,prefix:config.botPrefix,tickSize}),gateway=new AdaptiveMakerGateway({config,executor,accountProvider,marketData,connectivity:()=>conn,clockSkewMs:()=>clockSkew,tickSize,feeBps:finite(process.env.V48_MAKER_FEE_BPS,1.2),adverseSelectionBps:finite(process.env.V48_ADVERSE_SELECTION_BPS,1),imbalanceBps:finite(process.env.V48_IMBALANCE_BPS,2)});
const connectPublic=()=>{if(stopping)return;try{publicWs?.close();}catch{}publicWs=new WebSocket('wss://stream.toobit.com/quote/ws/v1');publicWs.onopen=()=>{conn.publicWs=true;publicWs.send(JSON.stringify({symbol:config.symbol,topic:'bookTicker',event:'sub'}));publicWs.send(JSON.stringify({symbol:config.symbol,topic:'diffDepth',event:'sub',params:{binary:false}}));};publicWs.onmessage=(ev)=>{let m;try{m=JSON.parse(String(ev.data));}catch{return;}const now=Date.now();if(m?.topic==='bookTicker'||m?.data?.e==='bookTicker')gateway.onBookTicker(m,now).catch(()=>{});else if(m?.topic==='diffDepth')gateway.onDiffDepth(m,now).catch(()=>{});};publicWs.onclose=()=>{conn.publicWs=false;if(!stopping)setTimeout(connectPublic,1500);};publicWs.onerror=()=>{conn.publicWs=false;};};
const connectPrivate=async()=>{if(stopping||conn.privateWs)return;try{const d=await bridge.call('/listen-key',{method:'POST',body:{}});listenKey=String(d.listenKey||'');if(!listenKey)throw new Error('LISTEN_KEY_EMPTY');privateWs=new WebSocket(`wss://stream.toobit.com/api/v1/ws/${encodeURIComponent(listenKey)}`);privateWs.onopen=()=>{conn.privateWs=true;};privateWs.onmessage=(ev)=>{let m;try{m=JSON.parse(String(ev.data));}catch{return;}gateway.onPrivateEvent(m,Date.now()).catch(()=>{});};privateWs.onclose=()=>{conn.privateWs=false;listenKey='';if(!stopping)setTimeout(()=>connectPrivate().catch(()=>{}),1500);};privateWs.onerror=()=>{conn.privateWs=false;};}catch{conn.privateWs=false;if(!stopping)setTimeout(()=>connectPrivate().catch(()=>{}),5000);}};connectPublic();await connectPrivate();
setInterval(()=>{try{if(publicWs?.readyState===1)publicWs.send(JSON.stringify({ping:Date.now()}));if(privateWs?.readyState===1)privateWs.send(JSON.stringify({ping:Date.now()}));}catch{}},30000);setInterval(()=>{if(listenKey)bridge.call('/listen-key',{method:'PUT',body:{listenKey}}).catch(()=>{});},25*60*1000);setInterval(async()=>{try{const s=Date.now(),r=await fetch('https://api.toobit.com/api/v1/time',{cache:'no-store'}),e=Date.now(),d=await r.json();if(Number.isFinite(Number(d.serverTime)))clockSkew=Number(d.serverTime)-(s+(e-s)/2);}catch{}},10000);setInterval(()=>gateway.watchdog(Date.now()).catch(()=>{}),1000);setInterval(async()=>{try{const d=await bridge.call('/command'),c=d.command;if(!c)return;const st=await gateway.handleCommand(c.action,Date.now());await bridge.call('/ack',{method:'POST',body:{id:c.id,state:st.state}});}catch{}},1000);setInterval(async()=>{try{await bridge.call('/telemetry',{method:'POST',body:gateway.telemetrySnapshot(Date.now())});await bridge.call('/runtime',{method:'POST',body:gateway.runtimeSnapshot(Date.now())});}catch{}},2000);
const shutdown=async()=>{stopping=true;try{await gateway.handleCommand('DISARM');}catch{}try{if(listenKey)await bridge.call('/listen-key',{method:'DELETE',body:{listenKey}});}catch{}try{publicWs?.close();privateWs?.close();}catch{}await sleep(50);process.exit(0);};process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);return gateway;}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){runProduction().catch((e)=>{console.error('fatal',String(e?.message||e));process.exit(1);});}
